program WtSystem;

uses
  Vcl.Forms,
  Conexao in 'db\Conexao.pas',
  Model in 'model\Model.pas',
  User in 'model\User.pas',
  Empresa in 'model\Empresa.pas',
  Repository in 'repository\Repository.pas',
  Helper in 'helper\Helper.pas',
  uformAuthLogin in 'form\uformAuthLogin.pas' {formAuthLogin},
  uformUserCreateEdit in 'form\uformUserCreateEdit.pas' {formAuthCreateUser},
  AuthService in 'service\AuthService.pas',
  uformPrincipal in 'form\uformPrincipal.pas' {formPrincipal},
  uformEmpresaCreateEdit in 'form\uformEmpresaCreateEdit.pas' {formAuthCreateEmpresa},
  Pessoa in 'model\Pessoa.pas',
  uformPessoaCreateEdit in 'form\uformPessoaCreateEdit.pas' {formPessoaCreateEdit},
  uformPessoaList in 'form\uformPessoaList.pas' {formPessoaList},
  Permission in 'model\Permission.pas',
  Role in 'model\Role.pas',
  uformUserList in 'form\uformUserList.pas' {formUserList},
  uformPermissionList in 'form\uformPermissionList.pas' {formPermissionList},
  uformPermissionCreateEdit in 'form\uformPermissionCreateEdit.pas' {formPermissionCreateEdit},
  uformRoleList in 'form\uformRoleList.pas' {formRoleList},
  uformRoleCreateEdit in 'form\uformRoleCreateEdit.pas' {formRoleCreateEdit},
  Unidade in 'model\Unidade.pas',
  Contabilista in 'model\Contabilista.pas',
  Conta in 'model\Conta.pas',
  Pagamento in 'model\Pagamento.pas',
  Recebimento in 'model\Recebimento.pas',
  Venda in 'model\Venda.pas',
  VendaItem in 'model\VendaItem.pas',
  Categoria in 'model\Categoria.pas',
  Trasnferencia in 'model\Trasnferencia.pas',
  Item in 'model\Item.pas',
  uformItemList in 'form\uformItemList.pas' {formItemList},
  uformItemCreateEdit in 'form\uformItemCreateEdit.pas' {formItemCreateEdit},
  uformUnidadeList in 'form\uformUnidadeList.pas' {formUnidadeList},
  uformUnidadeCreateEdit in 'form\uformUnidadeCreateEdit.pas' {formUnidadeCreateEdit},
  uformCategoriaList in 'form\uformCategoriaList.pas' {formCategoriaList},
  uformCategoriaCreateEdit in 'form\uformCategoriaCreateEdit.pas' {formCategoriaCreateEdit},
  uformContabilistaCreateEdit in 'form\uformContabilistaCreateEdit.pas' {formContabilistaCreateEdit},
  uformVendaCreateEdit in 'form\uformVendaCreateEdit.pas' {formVendaCreateEdit},
  CustomEditHelper in 'helper\CustomEditHelper.pas',
  uformVendaList in 'form\uformVendaList.pas' {formVendaList},
  NfeConfiguracao in 'model\NfeConfiguracao.pas',
  uformNfeConfiguracaoCreateEdit in 'form\uformNfeConfiguracaoCreateEdit.pas' {formNfeConfiguracaoCreateEdit},
  Nfe in 'model\Nfe.pas',
  NfeDet in 'model\NfeDet.pas',
  NfeDetIcms in 'model\NfeDetIcms.pas',
  NfeDetIpi in 'model\NfeDetIpi.pas',
  NfeDetPis in 'model\NfeDetPis.pas',
  NfeTotalIcms in 'model\NfeTotalIcms.pas',
  NfeTotalIssqn in 'model\NfeTotalIssqn.pas',
  NfeDetPisSt in 'model\NfeDetPisSt.pas',
  NfeDetCofins in 'model\NfeDetCofins.pas',
  NfeDetCofinsSt in 'model\NfeDetCofinsSt.pas',
  NfeDetIi in 'model\NfeDetIi.pas',
  NfeDetIssqn in 'model\NfeDetIssqn.pas',
  NfeDetIcmsUfDest in 'model\NfeDetIcmsUfDest.pas',
  NfeRefNfe in 'model\NfeRefNfe.pas',
  NfeRefCte in 'model\NfeRefCte.pas',
  NfeRefNf in 'model\NfeRefNf.pas',
  NfeRefNfp in 'model\NfeRefNfp.pas',
  NfeRefEcf in 'model\NfeRefEcf.pas',
  NfeDetDi in 'model\NfeDetDi.pas',
  NfeDetAdi in 'model\NfeDetAdi.pas',
  NfeDetExport in 'model\NfeDetExport.pas',
  NfeDetRastro in 'model\NfeDetRastro.pas',
  NfeDetVeic in 'model\NfeDetVeic.pas',
  NfeDetMed in 'model\NfeDetMed.pas',
  NfeDetArma in 'model\NfeDetArma.pas',
  NfeDetComb in 'model\NfeDetComb.pas',
  NfeRetirada in 'model\NfeRetirada.pas',
  NfeEntrega in 'model\NfeEntrega.pas',
  NfeTransp in 'model\NfeTransp.pas',
  NfeTranspRet in 'model\NfeTranspRet.pas',
  NfeTranspVeic in 'model\NfeTranspVeic.pas',
  NfeTranspVol in 'model\NfeTranspVol.pas',
  NfeTranspVolLacres in 'model\NfeTranspVolLacres.pas',
  NfeTranspReboque in 'model\NfeTranspReboque.pas',
  NfeCobrFat in 'model\NfeCobrFat.pas',
  NfeCobrDup in 'model\NfeCobrDup.pas',
  NfePag in 'model\NfePag.pas',
  NfeExporta in 'model\NfeExporta.pas',
  NfeCompra in 'model\NfeCompra.pas',
  NfeCana in 'model\NfeCana.pas',
  NfeCanaFordia in 'model\NfeCanaFordia.pas',
  NfeCanaDeduc in 'model\NfeCanaDeduc.pas',
  NfeTotalRettrib in 'model\NfeTotalRettrib.pas',
  OperacaoFiscal in 'model\OperacaoFiscal.pas',
  GrupoTributario in 'model\GrupoTributario.pas',
  uformOperacaoFiscalList in 'form\uformOperacaoFiscalList.pas' {formOperacaoFiscalList},
  uformOperacaoFiscalCreateEdit in 'form\uformOperacaoFiscalCreateEdit.pas' {formOperacaoFiscalCreateEdit},
  uformGrupoTributarioList in 'form\uformGrupoTributarioList.pas' {formGrupoTributarioList},
  uformGrupoTributarioCreateEdit in 'form\uformGrupoTributarioCreateEdit.pas' {formGrupoTributarioCreateEdit},
  uformConfiguracaoFiscalList in 'form\uformConfiguracaoFiscalList.pas' {formConfiguracaoFiscalList},
  ConfiguracaoFiscal in 'model\ConfiguracaoFiscal.pas',
  uformConfiguracaoFiscalCreateEdit in 'form\uformConfiguracaoFiscalCreateEdit.pas' {formConfiguracaoFiscalCreateEdit},
  ConfiguracaoFiscalIcms in 'model\ConfiguracaoFiscalIcms.pas',
  uformConfiguracaoFiscalIcmsCreateEdit in 'form\uformConfiguracaoFiscalIcmsCreateEdit.pas' {formConfiguracaoFiscalIcmsCreateEdit},
  ConfiguracaoFiscalIpi in 'model\ConfiguracaoFiscalIpi.pas',
  ConfiguracaoFiscalPis in 'model\ConfiguracaoFiscalPis.pas',
  ConfiguracaoFiscalCofins in 'model\ConfiguracaoFiscalCofins.pas',
  uformNfeList in 'form\uformNfeList.pas' {formNfeList},
  uformNfeCreateEdit in 'form\uformNfeCreateEdit.pas' {formNfeCreateEdit},
  uformNfeDetCreateEdit in 'form\uformNfeDetCreateEdit.pas' {formNfeDetCreateEdit},
  ViewCfIcms in 'model\ViewCfIcms.pas',
  ViewCfIpi in 'model\ViewCfIpi.pas',
  ViewCfPis in 'model\ViewCfPis.pas',
  ViewCfCofins in 'model\ViewCfCofins.pas',
  uformNcmIBPTax in 'form\uformNcmIBPTax.pas' {formNcmIBPTax},
  Ncm in 'model\Ncm.pas',
  FormaRecebimento in 'model\FormaRecebimento.pas',
  VendaRecebimento in 'model\VendaRecebimento.pas',
  uformFormaRecebimentoList in 'form\uformFormaRecebimentoList.pas' {formFormaRecebimentoList},
  uformFormaRecebimentoCreateEdit in 'form\uformFormaRecebimentoCreateEdit.pas' {formFormaRecebimentoCreateEdit},
  uformVendaFinalizar in 'form\uformVendaFinalizar.pas' {formVendaFinalizar},
  uformRecebimentoList in 'form\uformRecebimentoList.pas' {formRecebimentoList},
  uformRecebimentoCreateEdit in 'form\uformRecebimentoCreateEdit.pas' {formRecebimentoCreateEdit},
  uformContaList in 'form\uformContaList.pas' {formContaList},
  uformContaCreateEdit in 'form\uformContaCreateEdit.pas' {formContaCreateEdit},
  Boleto in 'model\Boleto.pas',
  Cedente in 'model\Cedente.pas',
  BoletoConfiguracao in 'model\BoletoConfiguracao.pas',
  uformBoletoCreateEdit in 'form\uformBoletoCreateEdit.pas' {formBoletoCreateEdit},
  BoletoRemessa in 'model\BoletoRemessa.pas',
  uformBoletoRemessaList in 'form\uformBoletoRemessaList.pas' {formBoletoRemessaList},
  BoletoRetorno in 'model\BoletoRetorno.pas',
  uformBoletoRetornoList in 'form\uformBoletoRetornoList.pas' {formBoletoRetornoList},
  udmRepository in 'dm\udmRepository.pas' {dmRepository: TDataModule},
  uformMensagem in 'form\uformMensagem.pas' {formMensagem},
  uformPagamentoList in 'form\uformPagamentoList.pas' {formPagamentoList},
  uformPagamentoCreateEdit in 'form\uformPagamentoCreateEdit.pas' {formPagamentoCreateEdit},
  Vcl.Themes,
  Vcl.Styles,
  EmpresaConfiguracao in 'model\EmpresaConfiguracao.pas',
  uformEmpresaConfiguracaoCreateEdit in 'form\uformEmpresaConfiguracaoCreateEdit.pas' {formEmpresaConfiguracaoCreateEdit},
  uformVendaParcelamento in 'form\uformVendaParcelamento.pas' {formVendaParcelamento},
  uformInfCplList in 'form\uformInfCplList.pas' {formInfCplList},
  NfeInfcpl in 'model\NfeInfcpl.pas',
  NfeInfadfisco in 'model\NfeInfadfisco.pas',
  uformInfCplCreateEdit in 'form\uformInfCplCreateEdit.pas' {formInfCplCreateEdit},
  uformInfadfiscoList in 'form\uformInfadfiscoList.pas' {formInfadfiscoList},
  uformInfadfiscoCreateEdit in 'form\uformInfadfiscoCreateEdit.pas' {formInfadfiscoCreateEdit},
  Compra in 'model\Compra.pas',
  CompraItem in 'model\CompraItem.pas',
  uformCompraList in 'form\uformCompraList.pas' {formCompraList},
  uformCompraCreateEdit in 'form\uformCompraCreateEdit.pas' {formCompraCreateEdit},
  uformCompraFinalizar in 'form\uformCompraFinalizar.pas' {formCompraFinalizar},
  uformDescription in 'form\uformDescription.pas' {formDescription},
  uformEstoqueList in 'form\uformEstoqueList.pas' {formEstoqueList},
  uformItemMovimentoList in 'form\uformItemMovimentoList.pas' {formItemMovimentoList},
  ItemInventario in 'model\ItemInventario.pas',
  uformItemInventarioCreate in 'form\uformItemInventarioCreate.pas' {formItemInventarioCreate},
  uformNfeRecebidasList in 'form\uformNfeRecebidasList.pas' {formNfeRecebidasList},
  uformNfeRecebidaDetList in 'form\uformNfeRecebidaDetList.pas' {formNfeRecebidaDetList},
  ItemCodigo in 'model\ItemCodigo.pas',
  uformNfeRecebidaDetEdit in 'form\uformNfeRecebidaDetEdit.pas' {formNfeRecebidaDetEdit},
  UnidadeConversao in 'model\UnidadeConversao.pas',
  Wt in 'model\Wt.pas',
  uformBloqueio in 'form\uformBloqueio.pas' {formBloqueio},
  uformItemUnidadeConversorList in 'form\uformItemUnidadeConversorList.pas' {formItemUnidadeConversorList},
  uformItemUnidadeConversorCreateEdit in 'form\uformItemUnidadeConversorCreateEdit.pas' {formItemUnidadeConversorCreateEdit},
  UnidadeConversaoCodigo in 'model\UnidadeConversaoCodigo.pas',
  uformCompraItensAjuste in 'form\uformCompraItensAjuste.pas' {formCompraItensAjuste},
  uformCedenteCreateEdit in 'form\uformCedenteCreateEdit.pas' {formCedenteCreateEdit},
  uformNfeEmpresaList in 'form\uformNfeEmpresaList.pas' {formNfeEmpresaList},
  ViewContaExtrato in 'model\ViewContaExtrato.pas',
  Sped in 'model\Sped.pas',
  uformSPEDList in 'form\uformSPEDList.pas' {formSPEDList},
  uformSPEDCreateEdit in 'form\uformSPEDCreateEdit.pas' {formSPEDCreateEdit},
  ViewSped0150 in 'model\ViewSped0150.pas',
  ViewSped0190 in 'model\ViewSped0190.pas',
  ViewSped0200 in 'model\ViewSped0200.pas',
  ViewSpedC100 in 'model\ViewSpedC100.pas',
  ViewSpedC190 in 'model\ViewSpedC190.pas',
  Cartao in 'model\Cartao.pas',
  uformCartaoList in 'form\uformCartaoList.pas' {formCartaoList},
  uformCartaoCreateEdit in 'form\uformCartaoCreateEdit.pas' {formCartaoCreateEdit},
  uformCartaoParcelamento in 'form\uformCartaoParcelamento.pas' {formCartaoParcelamento},
  uformOrcamentoList in 'form\uformOrcamentoList.pas' {formOrcamentoList},
  uformPrint in 'form\uformPrint.pas' {formPrint},
  NfeNumero in 'model\NfeNumero.pas',
  uformNfeNumeroList in 'form\uformNfeNumeroList.pas' {formNfeNumeroList},
  uformNfeNumeroCreateEdit in 'form\uformNfeNumeroCreateEdit.pas' {formNfeNumeroCreateEdit},
  uformCompraOrcamentoList in 'form\uformCompraOrcamentoList.pas' {formCompraOrcamentoList},
  Terminal in 'model\Terminal.pas',
  uformTerminalList in 'form\uformTerminalList.pas' {formTerminalList},
  uformTerminalCreateEdit in 'form\uformTerminalCreateEdit.pas' {formTerminalCreateEdit},
  Turno in 'model\Turno.pas',
  uformTurnoList in 'form\uformTurnoList.pas' {formTurnoList},
  uformBase in 'form\uformBase.pas' {formBase},
  uformTurnoCreateEdit in 'form\uformTurnoCreateEdit.pas' {formTurnoCreateEdit};

{$R *.res}

begin
  Application.Initialize;
  Application.Title := 'WT - SYSTEM';
  Application.MainFormOnTaskbar:= False;
  Application.CreateForm(TdmRepository, dmRepository);
  Application.CreateForm(TformPrincipal, formPrincipal);
  Application.Run;
end.
